import PocketBase from 'pocketbase';

const pb = new PocketBase('http://127.0.0.1:8090');

const json = [
  '가모라 (Gamora)',
  '갤럭투스 (Galactus)',
  '갬빗 (Gambit)',
  '고스트 라이더 (Ghost Rider)',
  '구스 (Goose)',
  '그루트 (Groot)',
  '그린 고블린 (Green Goblin)',
  '기간토 (Giganto)',
  '나이트크롤러 (Nightcrawler)',
  '나키아 (Nakia)',
  '널 (Knull)',
  '네이머 (Namor)',
  '노바 (Nova)',
  '닉 퓨리 (Nick Fury)',
  '닌자 (Ninja)',
  '다크호크 (Darkhawk)',
  '닥터 둠 (Doctor Doom)',
  '닥터 스트레인지 (Doctor Strange)',
  '닥터 옥토퍼스 (Doctor Octopus)',
  '대거 (Dagger)',
  '데드풀 (Deadpool)',
  '데몬 (Demon)',
  '데브리 (Debrii)',
  '데빌 다이노소어 (Devil Dinosaur)',
  '데스 (Death)',
  '데스록 (Deathlok)',
  '데어데블 (Daredevil)',
  '도미노 (Domino)',
  '둠봇 (Doombot)',
  '드라큘라 (Dracula)',
  '드랙스 (Drax)',
  '드론 (Drone)',
  '디스트로이어 (Destroyer)',
  '라이노 (Rhino)',
  '랩터 (Raptor)',
  '레드 스컬 (Red Skull)',
  '레스큐 (Rescue)',
  '레이디 시프 (Lady Sif)',
  '로그 (Rogue)',
  '로켓 라쿤 (Rocket Raccoon)',
  '록 (Rock)',
  '록슬라이드 (Rockslide)',
  '록조 (Lockjaw)',
  '루크 케이지 (Luke Cage)',
  '리더 (Leader)',
  '리얼리티 스톤 (Reality Stone)',
  '리저드 (Lizard)',
  '리치 (Leech)',
  '마리아 힐 (Maria Hill)',
  '마인드 스톤 (Mind Stone)',
  '마일스 모랄레스 (Miles Morales)',
  '막시무스 (Maximus)',
  '매그니토 (Magneto)',
  '매직 (Magik)',
  '맨티스 (Mantis)',
  '멀티플맨 (Multiple Man)',
  '메두사 (Medusa)',
  '모르도 남작 (Baron Mordo)',
  '모비우스 (Morbius)',
  '모조 (Mojo)',
  '모프 (Morph)',
  '몬스터 (Monster)',
  '묠니르 (Mjolnir)',
  '문 걸 (Moon Girl)',
  '문 나이트 (Moon Knight)',
  '미스터 네거티브 (Mister Negative)',
  '미스터 시니스터 (Mister Sinister)',
  '미스터 판타스틱 (Mister Fantastic)',
  '미스테리오 (Mysterio)',
  '미스테리오? (Mysterio?)',
  '미스티 나이트 (Misty Knight)',
  '미스틱 (Mystique)',
  '바스트 (Bast)',
  '바이퍼 (Viper)',
  '발키리 (Valkyrie)',
  '버키 반스 (Bucky Barnes)',
  '벌처 (Vulture)',
  '베놈 (Venom)',
  '보이드 (The Void)',
  '브루드 (Brood)',
  '브루드링 (Broodling)',
  '블랙 볼트 (Black Bolt)',
  '블랙 위도우 (Black Widow)',
  '블랙 캣 (Black Cat)',
  '블랙 팬서 (Black Panther)',
  '블레이드 (Blade)',
  '블루 마블 (Blue Marvel)',
  '비브라늄 (Vibranium)',
  '비숍 (Bishop)',
  '비스트 (Beast)',
  '비전 (Vision)',
  '사이클롭스 (Cyclops)',
  '사일록 (Psylocke)',
  '샌드맨 (Sandman)',
  '샹치 (Shang-Chi)',
  '선스팟 (Sunspot)',
  '세라 (Sera)',
  '세레브로 (Cerebro)',
  '세이버투스 (Sabretooth)',
  '센트리 (Sentry)',
  '센티널 (Sentinel)',
  '소드마스터 (Sword Master)',
  '소울 스톤 (Soul Stone)',
  '쇼커 (Shocker)',
  '쉬헐크 (She-Hulk)',
  '슈리 (Shuri)',
  '슈퍼 스크럴 (Super-Skrull)',
  '스웜 (Swarm)',
  '스칼렛 위치 (Scarlet Witch)',
  '스콜피온 (Scorpion)',
  '스쿼럴 (Squirrel)',
  '스쿼럴걸 (Squirrel Girl)',
  '스타로드 (Star-Lord)',
  '스톰 (Storm)',
  '스트롱 가이 (Strong Guy)',
  '스파이더맨 (Spider-Man)',
  '스파이더우먼 (Spider-Woman)',
  '스페이스 스톤 (Space Stone)',
  '스펙트럼 (Spectrum)',
  '시니스터 클론 (Sinister Clone)',
  '실버 서퍼 (Silver Surfer)',
  '심비오트 (Symbiote)',
  '씽 (The Thing)',
  '아담 워록 (Adam Warlock)',
  '아르님 졸라 (Arnim Zola)',
  '아머 (Armor)',
  '아메리카 차베즈 (America Chavez)',
  '아이스맨 (Iceman)',
  '아이언 피스트 (Iron Fist)',
  '아이언맨 (Iron Man)',
  '아이언하트 (Ironheart)',
  '아투마 (Attuma)',
  '아포칼립스 (Apocalypse)',
  '안젤라 (Angela)',
  '애거사 하크니스 (Agatha Harkness)',
  '앤트맨 (Ant-Man)',
  '어보미네이션 (Abomination)',
  '업소빙맨 (Absorbing Man)',
  '에보니 모 (Ebony Maw)',
  '에어로 (Aero)',
  '에이전트 13 (Agent 13)',
  '에이전트 콜슨 (Agent Coulson)',
  '엔젤 (Angel)',
  '엘렉트라 (Elektra)',
  '옐로재킷 (Yellowjacket)',
  '오딘 (Odin)',
  '오르카 (Orka)',
  '오메가 레드 (Omega Red)',
  '오코예 (Okoye)',
  '온슬로트 (Onslaught)',
  '와스프 (Wasp)',
  '욘두 (Yondu)',
  '울버린 (Wolverine)',
  '울트론 (Ultron)',
  '울프스베인 (Wolfsbane)',
  '워패스 (Warpath)',
  '웡 (Wong)',
  '웨이브 (Wave)',
  "위도우즈 바이트 (Widow's Bite)",
  '윈터 솔저 (Winter Soldier)',
  "음바쿠 (M'Baku)",
  '인비저블우먼 (Invisible Woman)',
  '인챈트리스 (Enchantress)',
  '인피너트 (The Infinaut)',
  '일렉트로 (Electro)',
  '일루전! (Illusion!)',
  '저거노트 (Juggernaut)',
  '제로 (Zero)',
  '제시카 존스 (Jessica Jones)',
  '제인 포스터 마이티 토르 (Jane Foster Mighty Thor)',
  '주빌리 (Jubilee)',
  '주시자 우아투 (Uatu the Watcher)',
  '집행관 로난 (Ronan the Accuser)',
  '카니지 (Carnage)',
  '카자르 (Ka-Zar)',
  '캡틴 마블 (Captain Marvel)',
  '캡틴 아메리카 (Captain America)',
  '케이블 (Cable)',
  '코르그 (Korg)',
  '코스모 (Cosmo)',
  '콜렉터 (The Collector)',
  '콜로서스 (Colossus)',
  '콜린 윙 (Colleen Wing)',
  '퀘이크 (Quake)',
  '퀵실버 (Quicksilver)',
  '퀸젯 (Quinjet)',
  '크레이븐 (Kraven)',
  '크로스본즈 (Crossbones)',
  '크리스탈 (Crystal)',
  '클로 (Klaw)',
  '클록 (Cloak)',
  '킬몽거 (Killmonger)',
  '킹핀 (Kingpin)',
  '타노스 (Thanos)',
  '타이거 스피릿 (Tiger Spirit)',
  '타이타니아 (Titania)',
  '타이포이드 메리 (Typhoid Mary)',
  '타임 스톤 (Time Stone)',
  '태스크마스터 (Taskmaster)',
  '토르 (Thor)',
  '파워 스톤 (Power Stone)',
  '팔콘 (Falcon)',
  '패트리어트 (Patriot)',
  '퍼니셔 (Punisher)',
  '포지 (Forge)',
  '폴라리스 (Polaris)',
  '프로페서 X (Professor X)',
  '해즈맷 (Hazmat)',
  '헐크 (Hulk)',
  '헐크버스터 (Hulkbuster)',
  '헤임달 (Heimdall)',
  '헬라 (Hela)',
  '헬리캐리어 (Helicarrier)',
  '헬카우 (Hellcow)',
  '호크아이 (Hawkeye)',
  '홉고블린 (Hobgoblin)',
  '화이트 퀸 (White Queen)',
  '화이트 타이거 (White Tiger)',
  '후드 (The Hood)',
  '휴먼 토치 (Human Torch)',
];
(async () => {
  const cards = await pb.collection('cards').getFullList(300);
  for (const c of cards) {
    try {
      const kr = c.name.split(' (')[0];
      const en = c.name.split(' (')[1].replace(')', '');
      console.log(`${kr} ${en}`);
      await pb.collection('cards').update(c.id, {
        ...c,
        name: kr,
        en,
      });
    } catch (e) {
      console.error(e.message);
    }
  }
})();
